#!/usr/bin/perl

=head1 NAME

    MetaGene

=head1 SYNOPSIS

	perl MetaGene -i seqFile.fasta -aa seqFile.faa
    perl MetaGene [-i file.fasta] [-aa file.faa] [-nt file.fna] [-csv file.csv] [-gff file.gff]

=head1 DESCRIPTION

    This script automatically predict gene/protein from a fasta file withe MetaGeneAnnotator predictor tool
    (Hideki Noguchi, Takeaki Taniguchi and Takehiko Itoh, DNA Research, 2008).
    The name of the fasta file is use in this script and present in output file. If you want to use MEnTALI 
    pipeline for different sample, please give specify a diffrent name for each sample. 
 

=head1 OPTIONS
    
    --Help|help|h, produces this help file.    

    --Verbose[no-Verbose]|verbose[no-verbose]|v[no-v]
    boolean option to print out warnings during execution. 
    Warnings and errors are redirected to STDERR.
    Defaults to no verbose (silent mode).
    
    --force /!\ force the script by ERASED early project. 
    
    -i, nucleotid fasta file as input.
    
    --procedure [m|s]	
		Multi or Single species option in MetageneAnnotator. 
		Meta or single parameter for -p parameter in prodigal.
		(default 'm') 
    
    --mga, call existing mga file for nucleotid fasta file (-i).

    -nt, output predicted gene in fasta format.

    -aa, output predicted protein in fasta format.

    -gff, output predicted gene in gff format.

    -csv, output predicted protein and gene in tabular format. 


=head1 AUTHORS

HOCHART Corentin

=head1 VERSION

version 0.3

=head1 DATE

Creation : 08.06.2015
Last modification : 05.04.2017

=cut

#~ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
# libraries
use warnings;
use strict;
use Bio::Seq;
use Bio::SeqFeature::Generic;
use Bio::Perl;
use FindBin;
use Getopt::Long;
use Pod::Usage;
use POSIX;


#~ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#scalars
my $help; 		# help flag
my $verbose;	# debugging flag
my $exe = $FindBin::RealScript; # executable path
my $gff_factory = Bio::Tools::GFF->new(-gff_version=>3); # gff version to use 
my $version; # version flag
my $VERSION="0.3"; # script version
my $force; # force flag
my $date=date(); # date 

my $procedure="m";
my $GFF;
my $amin;
my $nucleic;
my $gff="";
my $csv;
my $counter = 0; #counter for file name in file verification fonction
my $input_fasta;

my $VIEWDATASQUARE = 3 ;
my $sid;	#sequence id
my $gc_count;
my $snb=1; 	#sequence number
my $gnb=1 ;	#gene number

#~ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#tables

#~ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#hashes
my %seq;

#~ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#function
sub error {
	# management of error messages and help page layout, will stop execution
	# local arguments passed:1st, error message to output
	my $error = shift;
	my $filename = ($0);
	pod2usage(-message => "$filename (error): $error. Execution halted.", -verbose => 1, -noperldoc => 1);
	exit(2);
}

sub warning {
	# management of warnings and execution carry on
	# local arguments passed: 1st, warning message to output
	if ($verbose) {
		my $message = shift;
		my $filename = $0;
		warn("$filename (info): ".$message."\n");
	}
}

sub date { 
  my $time = shift || time;    #$time par defaut vaut le time actuel 
  my ( $seconde, $minute, $heure, $jour, $mois, $annee, $jour_semaine, $jour_annee, $heure_hiver_ou_ete ) 
    = localtime($time); 
  $mois  += 1; 
  $annee += 1900; 
  
  # On rajoute 0 si le chiffre est compris entre 1 et 9 
  foreach ( $seconde, $minute, $heure, $jour, $mois, $annee ) { 
    s/^(\d)$/0$1/; 
  } 
  
  my %ladate = ( 
    "date"         => "$jour-$mois-$annee", 
    "heure"        => "$heure:$minute:$seconde", 
    "jour_semaine" => $jour_semaine, 
    "jour_annee"   => $jour_annee, 
    "hiverOuEte"   => $heure_hiver_ou_ete, 
  ); 
  return \%ladate; 
}

sub fasta_format {
	my $seq=shift;
	$seq=~s/(.{60})/$1\n/g;
	chomp $seq;
    return $seq;
}

sub fileVerification{
	my $file = $_[0] ;
	my $name = "INPUT".$counter ;
	if ($file){
		no strict "refs";
		open ($name,$file) or &error("Unable to read '$file' from '--$_[1]' option !")
	}
	$counter ++ ;
	return
}

sub find_exe {
	my $tool = shift;
	for my $dir (File::Spec->path) {
		my $exe = File::Spec->catfile($dir, $tool);
		return $exe if -x $exe; 
	}
	return;
}

sub version {
  print STDERR "$exe $VERSION\n";
  exit;
}

#~ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

MAIN: {
	GetOptions(
			"Help|help|h" 			=> \$help,		#help flag
			"Verbose|verbose|v!" 	=> \$verbose,	#verbose flag
			"version!"				=> \$version,	#version flag
			"force!"				=> \$force,		#force flag
			
			"i|input=s"	 			=> \$input_fasta,	#input file in fasta format.
			"procedure=s"			=> \$procedure,		#prediction procedure for mga.
			
			"aa=s" 					=> \$amin,		#output for predicted proteins in fasta format.
			"nt=s" 					=> \$nucleic,	#output for predicted genes in fasta format.
			"gff=s" 				=> \$gff,		#output for predicted genes in gff format.
			"csv=s" 				=> \$csv,
		);
	
	&version if ($version);
	
	if ($help) {
		pod2usage(-verbose => 2, -noperldoc => 1);
		exit;
	}
	my $user = $ENV{ USER };
	&warning("Hi $user! Let's do some good jobs together.");
	&warning("First. Check tools and options.");
	
#~ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
#~ check mga tools 
my $fp = find_exe('mga');
&error("Can't find 'mga' in your \$PATH") if !$fp;

#~ check files and options

unless ($input_fasta){&error("No contigs file")}
&fileVerification ("$input_fasta","input_fasta");

&error("Wrong parameter for '--procedure' option.") unless $procedure eq "m" || $procedure eq "s";  

if($amin){if (-e $amin){
	unless($force){&error("$amin already exists. Use '--force' option to overwrite.")}
	`rm $amin`
}}
if($nucleic){if (-e $nucleic){
	unless($force){&error("$nucleic already exists. Use '--force' option to overwrite.")}
	`rm $nucleic`
}}
if($gff){if (-e $gff){
	unless($force){&error("$gff already exists. Use '--force' option to overwrite.")}
	else{`rm $gff`}
}}
if($csv){if (-e $csv){
	unless($force){&error("$csv already exists. Use '--force' option to overwrite.")}
	else{`rm $csv`}
}}


#~ . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
&warning("Everything seems to be good.");
&warning("Start of script.");

&warning("Load fasta file.");	
my $seqio_object = Bio::SeqIO->new(  -format => 'Fasta',
									-file   => $input_fasta,
						);


my $cmd="mga $input_fasta -$procedure";
&warning("Running: '$cmd'");
open MetaGene, "$cmd|";
while (<MetaGene>){
	chomp;
	if(m/^# gc = (\S+),/){$gc_count=$1}
	elsif(m/^# self/){next}
	elsif(m/^# (\S+)/){$sid = $1}
	else {
		(my $gene_id,my $start,my $end,my $strand,my $frame,my $partial,my $score,my $model,my $rbs_s,my $rbs_e,my $rbs_sc)=split(/\t/);
		push @{$seq{$sid}{FEATURE}}, Bio::SeqFeature::Generic->new( 
			-primary    => "CDS", 
			-seq_id     => $sid,
			-source     => "mga",
			-start      => $start,
			-end        => $end,
			-strand     => $strand,
			-score      => $score,
			-frame      => $frame,
			-tag        => {
				'partial' 	=> $partial,
			},
		);
	}
}
close MetaGene;

&warning("Print output file.");
if ($csv){
	open (CSV, ">$csv");
	print CSV "Sequence ID\tStart\tStop\tStrand\tna_sequence\taa_sequence\n";
	close CSV;
}

# if($gff){
# 	open GFF, ">",$gff;
# 	select GFF;
# }
# print "##gff-version 3
# ##source: metagene:$VERSION
# ##date $date->{date}
# ##Type DNA\n";
# print join ("\t",'##seq_name','method','feature','start','end','score','strand','frame','gene',"\n");
		
while(my $seq_object = $seqio_object->next_seq() ){
	my $sseq=$seq_object->seq;
	my $sid=$seq_object->id;
	for my $feature ( sort { $a->start <=> $b->start } @{ $seq{$seq_object->id}{FEATURE} }) {
		my $start=$feature->start;
		my $end=$feature->end;
		my $frame=$feature->frame;
		my $strand=$feature->strand;
		my $ID = sprintf("%d\_%d",$snb,$gnb);
		$feature->add_tag_value('ID', $ID);
		if($strand eq "-"){
			my $length=$seq_object->length;
			$start=$length-$start+1;
			$end=$length-$end+1;
			($start,$end)=($end,$start);		
		}
		my $CDS=$seq_object->subseq(
			$start,
			$end
		);
		$CDS = Bio::Seq->new(
			'-seq' => $CDS,
		);	
		my $header=$feature->gff_string($gff_factory);
		$header=~m/(\S+\t){8}(\S+)/;
		$header=sprintf(">%s.%d # %d # %d # %d # %s\n",$sid,$gnb,$start,$end,$strand,$2);
		if($strand eq "-1"){
			if($nucleic){
				open (NT, ">>$nucleic");
				print NT $header;
				print NT &fasta_format($CDS->revcom->seq),"\n";
				close NT;
			}
			if($amin){
				open (AA, ">>$amin");
				print AA $header;
				print AA &fasta_format($CDS->revcom->translate(
							'-unknown' => 'X',
							'-frame' => $frame)->seq),"\n";
				close AA;
			}
			if ($csv){
				open (CSV, ">>$csv");
				print CSV "$sid.$gnb\t$start\t$end\t$strand\t";
				print CSV $CDS->revcom->seq, "\t";
				print CSV ($CDS->revcom->translate(
							'-unknown' => 'X',
							'-frame' => $frame)->seq),"\n";
				close CSV;
			}
		}
		else{
			if($nucleic){
				open (NT, ">>$nucleic");
				print NT $header;
				print NT &fasta_format($CDS->seq),"\n";
				close NT;
			}
			if($amin){
				open (AA, ">>$amin");
				print AA $header;
				print AA &fasta_format($CDS->translate(
							'-unknown' => 'X',
							'-frame' => $frame)->seq),"\n";
				close AA;
			}	
			if ($csv){
				open (CSV, ">>$csv");
				print CSV "$sid\_$gnb\t$start\t$end\t$strand\t";
				print CSV $CDS->seq, "\t";
				print CSV ($CDS->translate(
							'-unknown' => 'X',
							'-frame' => $frame)->seq),"\n";
				close CSV;
			}
		}
		# if($gff){
		# 	open GFF, ">>",$gff;
		# 	select GFF;
		# }
		# print $feature->gff_string($gff_factory),"\n";
		$gnb++;
	}
	$snb++;
}

&warning("End of script.");
}

